### PR TITLE
Update to three.js 0.78.0

### PR DESCRIPTION
**Pull request by karimbeyrouti**
Updated bower package and three.js to version 0.78.0

### CODE REVIEW

**Comment by tiye** [comment]
Do you have time to maintain this package? I mean all the following versions..

**Comment by karimbeyrouti** [comment]
Not an amazing amount of time: between a 10 month old baby, and work - I have precious little spare time. 

Although I would be happy to help where/when I can.

**Comment by tiye** [comment]
Please check this address https://github.com/jiyinyiyong/three.js/invitations

You may update the package directly without waiting for my responses. Don't forget to push a new tag after new version commits.

**Comment by karimbeyrouti** [comment]
How do you push a new tag, and do you need to publish to bower - or does it automatically get picked up ? 

is that the command to tag: 
`git tag -a 'v0.1.0' -m 'v0.1.0'`
`git push --follow-tags`
 ?

**Comment by tiye** [comment]
Bower will fetch code from GitHub, so:

``` bash
git tag 0.77.0 # don't add a `v`
git push origin 0.77.0 # --follow-tags should be fine but I used to push a tag directly
```

**Comment by karimbeyrouti** [comment]
Thank you - will merge - do this now, and try as much as I can to keep things updated.

**Comment by tiye** [comment]
And thank you for your help. I barely work on three.js and always missed its updates.

**Comment by karimbeyrouti** [comment]
you welcome - same to you - thanks for adding me to this repo.

**Pull request merged**
